# Generated by Django 6.0.6 on 2026-07-05 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceOB', '0002_alter_urlmodel_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AddConstraint(
            model_name='urlmodel',
            constraint=models.UniqueConstraint(fields=('user', 'url'), name='unique_user_url'),
        ),
    ]
