# Generated by Django 6.0.6 on 2026-07-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceOB', '0003_urlmodel_price_alter_urlmodel_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='url',
            field=models.URLField(max_length=1500),
        ),
    ]
