# Generated by Django 6.0.6 on 2026-07-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceOB', '0004_alter_urlmodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
