# Generated by Django 6.0.6 on 2026-07-08 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceOB', '0005_urlmodel_last_scraped_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageURLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='priceOB.urlmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MailBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_url', models.ManyToManyField(blank=True, to='priceOB.messageurlmodel')),
            ],
        ),
    ]
