# Generated by Django 6.0.6 on 2026-07-08 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceOB', '0006_messageurlmodel_mailbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='user',
            field=models.OneToOneField(default=24, on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
