# Generated by Django 6.0.6 on 2026-07-23 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceOB', '0007_mailbox_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageurlmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='msg_url',
            field=models.ManyToManyField(blank=True, related_name='mailbox_msg_url', to='priceOB.messageurlmodel'),
        ),
    ]
