# Generated by Django 6.0.6 on 2026-07-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceOB', '0008_messageurlmodel_created_at_alter_mailbox_msg_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageurlmodel',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
