# Generated by Django 6.0.6 on 2026-07-08 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceOB', '0006_messageurlmodel_mailbox'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mailbox',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_user', to='priceOB.mailbox'),
        ),
    ]
