# Generated by Django 6.0.6 on 2026-07-08 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_mailbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mailbox',
        ),
    ]
